USE ClothingStoreDB
GO

IF OBJECT_ID('Colors', 'U') IS NOT NULL
	DROP TABLE Colors
GO

CREATE TABLE Colors (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20) NOT NULL,
	HexCode CHAR(7) NOT NULL
)
GO

IF OBJECT_ID('Sizes', 'U') IS NOT NULL
	DROP TABLE Sizes
GO

CREATE TABLE Sizes (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(3)
)
GO

IF OBJECT_ID('Types', 'U') IS NOT NULL
	DROP TABLE Types
GO

CREATE TABLE Types (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20)
)
GO

IF OBJECT_ID('Raws', 'U') IS NOT NULL
	DROP TABLE Raws
GO

CREATE TABLE Raws (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20)
)
GO

IF OBJECT_ID('Statuses', 'U') IS NOT NULL
	DROP TABLE Statuses
GO

CREATE TABLE Statuses (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20)
)
GO
